const dummy = [
  {
    _id: { $oid: '62378fcadbf12400166ed1d8' },
    name: 'XYZ name',
    instituteName: 'DAV',
    examType: 'Pre Board Exam',
    board: 'CBSE',
    standard: 'XII',
    subject: 'Physics',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237923edbf12400166ed2de' },
    name: 'Kuch bhi name',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    standard: 'X',
    subject: 'Maths',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237907cdbf12400166ed1ee' },
    name: 'ABC name',
    instituteName: 'GD Goenka',
    examType: 'Board Exam',
    board: 'CBSE',
    standard: 'XII',
    subject: 'Chemistry',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237a05f2d310f001607b5ae' },
    name: 'Bekar name',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    standard: 'X',
    subject: 'History',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237923edbf12400166ed2d6' },
    name: 'Some name',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Pre-Board Exam',
    board: 'CBSE',
    standard: 'XII',
    subject: 'Maths',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237a05c2d310f001607b5a6' },
    name: 'New name',
    instituteName: 'Blue Bells School',
    examType: 'Board Exam',
    board: 'CBSE',
    standard: 'XII',
    subject: 'English',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237907ddbf12400166ed1f6' },
    name: 'Old name',
    instituteName: 'St.Pauls School',
    examType: 'Board Exam',
    board: 'CBSE',
    standard: 'X',
    subject: 'Social Science',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237923edbf1240016anks6ed2de' },
    name: 'New2 name',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    standard: 'XII',
    subject: 'Psychology',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237a05c2d310f001607b5a2' },
    name: 'Very old name',
    instituteName: 'Delhi Public School',
    examType: 'Pre-Board Exam',
    board: 'CBSE',
    standard: 'X',
    subject: 'Science',
    totalMarks: '75',
    time: '2.5',
  },
  {
    _id: { $oid: '6237923edbf12400166ed2d4' },
    name: 'Kuch bhi again name',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    standard: 'X',
    subject: 'Hindi',
    totalMarks: '75',
    time: '2.5',
  },
];

export default dummy;
