const dummy = [
  {
    _id: { $oid: '62378fcadbf12400166ed1d8' },
    title: 'XYZ Title',
    instituteName: 'DAV',
    examType: 'Pre Board Exam',
    board: 'CBSE',
    class: 'XII',
    subject: 'Physics',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237923edbf12400166ed2de' },
    title: 'Kuch bhi Title',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    class: 'X',
    subject: 'Maths',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237907cdbf12400166ed1ee' },
    title: 'ABC Title',
    instituteName: 'GD Goenka',
    examType: 'Board Exam',
    board: 'CBSE',
    class: 'XII',
    subject: 'Chemistry',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237a05f2d310f001607b5ae' },
    title: 'Bekar Title',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    class: 'X',
    subject: 'History',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237923edbf12400166ed2d6' },
    title: 'Some Title',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Pre-Board Exam',
    board: 'CBSE',
    class: 'XII',
    subject: 'Maths',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237a05c2d310f001607b5a6' },
    title: 'New Title',
    instituteName: 'Blue Bells School',
    examType: 'Board Exam',
    board: 'CBSE',
    class: 'XII',
    subject: 'English',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237907ddbf12400166ed1f6' },
    title: 'Old Title',
    instituteName: 'St.Pauls School',
    examType: 'Board Exam',
    board: 'CBSE',
    class: 'X',
    subject: 'Social Science',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237923edbf1240016anks6ed2de' },
    title: 'New2 Title',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    class: 'XII',
    subject: 'Psychology',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237a05c2d310f001607b5a2' },
    title: 'Very old Title',
    instituteName: 'Delhi Public School',
    examType: 'Pre-Board Exam',
    board: 'CBSE',
    class: 'X',
    subject: 'Science',
    totalMarks: '75',
    totalTime: '2.5',
  },
  {
    _id: { $oid: '6237923edbf12400166ed2d4' },
    title: 'Kuch bhi again Title',
    instituteName: 'Kendra Vidyalaya',
    examType: 'Board Exam',
    board: 'CBSE',
    class: 'X',
    subject: 'Hindi',
    totalMarks: '75',
    totalTime: '2.5',
  },
];

export default dummy;
