// eslint-disable-next-line import/prefer-default-export
export const Value = [
  {
    id: 1,
    question: 'Hello world is good?',
    option1: 'No',
    option2: 'IDK',
    option3: 'Yes',
    option4: 'Dont care',
    answer: 'Dont care',
    standard: 'X',
    subject: 'biology',
    chapter: 'Plant Kingdom',
    difficulty: 'Hard',
    imageurl: 'https://i.stack.imgur.com/i4yek.png',
  },
  {
    id: 2,
    question: 'Hello world is bad?',
    option1: 'No',
    option2: 'IDK',
    option3: 'Yes',
    option4: 'Dont care',
    answer: 'Dont care',
    standard: 'XI',
    subject: 'Math',
    chapter: 'Calculus',
    difficulty: 'Easy',
  },
  {
    id: 3,
    question: 'Hello world is worse?',
    option1: 'No',
    option2: 'IDK',
    option3: 'Yes',
    option4: 'Dont care',
    answer: 'Dont care',
    standard: 'IX',
    subject: 'History',
    chapter: 'Maharaja',
    difficulty: 'Easy',
  },
];
