name: Deployment

on:
  push: 
    branch: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: Ubuntu-latest
    steps:
      name: Pull latest code and build
      uses: appleboy/ssh-action@master
      with:
        host: 74.220.20.80
        username: root
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        script: |
          cd EnormoQB/Frontend
          git checkout main
          git pull
          npm run build

